<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <link href="css/bootstrap.min.css" rel="stylesheet">

    <link href="css/metisMenu.min.css" rel="stylesheet">

    <link href="css/timeline.css" rel="stylesheet">

    <link href="css/startmin.css" rel="stylesheet">

    <link href="css/morris.css" rel="stylesheet">

    <link href="css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <title>Odnowa Młodzi | Admin</title>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar" data-offset="60">
<div id="wrapper">

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Zmień</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <ul class="nav navbar-nav navbar-left navbar-top-links">
            <li><a href="/"><i class="fa fa-home fa-fw"></i> Strona Główna</a></li>
        </ul>

        <ul class="nav navbar-right navbar-top-links">
            <li class="dropdown navbar-inverse">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-comment fa-fw"></i> Brak nowych powiadomień
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text-center" href="#">
                            <strong>Zobacz historię</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Wyloguj</a>
            </li>
<!--            <li class="dropdown">-->
<!--                <a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
<!--                    <i class="fa fa-user fa-fw"></i> --><?php //echo $login; ?><!-- <b class="caret"></b>-->
<!--                </a>-->
<!--                <ul class="dropdown-menu dropdown-user">-->
<!--                    <li><a href="#"><i class="fa fa-user fa-fw"></i> Profil</a>-->
<!--                    </li>-->
<!--                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Ustawienia</a>-->
<!--                    </li>-->
<!--                    <li class="divider"></li>-->
<!--                    <li><a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Wyloguj</a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </li>-->
        </ul>

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <br /><br />
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="#" class="active"><i class="fa fa-dashboard fa-fw"></i> Podsumowanie</a>
                    </li>
<!--                <li>-->
<!--                    <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>-->
<!--                        <ul class="nav nav-second-level">-->
<!--                            <li>-->
<!--                                <a href="#">Second Level Item</a>-->
<!--                            </li>-->
<!--                            <li>-->
<!--                                <a href="#">Third Level <span class="fa arrow"></span></a>-->
<!--                                <ul class="nav nav-third-level">-->
<!--                                    <li>-->
<!--                                        <a href="#">Third Level Item</a>-->
<!--                                    </li>-->
<!--                                </ul>-->
<!--                            </li>-->
<!--                        </ul>-->
<!--                </li>-->

                    <li>
                        <a href="#" class=""><i class="fa fa-cog fa-fw"></i> Ustawienia Konta</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>

    <div id="page-wrapper">
        <div class="container-fluid">

            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Podsumowanie WSZYZDGIEGO</h1>
                </div>
            </div>

            <!-- ... Your content goes here ... -->

        </div>
    </div>

</div>
<script src="js/jquery.min.js"></script>
<script src="js/metisMenu.min.js"></script>
<script src="js/startmin.js"></script>
</body>
</html>