<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="/style/scripts.js"></script>
    <link rel="stylesheet" href="/style/login.css">
    <title>Odnowa Młodzi | Admin</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
            <div class="col-md-6 login">
                <form action="admin/login" method="post">
                    <p>
                        <label for="Login">Login:</label>
                        <input class="form-control input" type="text" name="login" id="Login">
                    </p>
                    <p>
                        <label for="Password">Hasło:</label>
                        <input class="form-control input" type="password" name="password" id="Password">
                    </p>
                    <p><a href="/"><button style="float: left;" type="button" class="btn button-left"><span>Cofnij</span></button></a>
                       <button style="float: right;" type="submit" class="btn button"><span>Wyślij</span></button></p>
                </form>
            </div>
        <div class="col-md-3"></div>
    </div>
</div>

<!--<form action="admin/register" method="post">-->
<!--    <p>-->
<!--        <label for="Login">Login:</label>-->
<!--        <input type="text" name="login" id="Login">-->
<!--    </p>-->
<!--    <p>-->
<!--        <label for="Password">Password:</label>-->
<!--        <input type="text" name="password" id="Password">-->
<!--    </p>-->
<!--    <input type="submit" value="Wyślij">-->
<!--</form>-->

</body>
</html>