<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="style/scripts.js"></script>
    <link rel="stylesheet" href="style/style2.css">
    <title>Odnowa Młodzi | Admin</title>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar" data-offset="60">
logowanie:
<form action="login" method="post">
    <p>
        <label for="Login">Login:</label>
        <input type="text" name="login" id="Login">
    </p>
    <p>
        <label for="Password">Password:</label>
        <input type="password" name="password" id="Password">
    </p>
    <input type="submit" value="Wyślij">
</form>

rejestracja:
<form action="register" method="post">
    <p>
        <label for="Login">Login:</label>
        <input type="text" name="login" id="Login">
    </p>
    <p>
        <label for="Password">Password:</label>
        <input type="text" name="password" id="Password">
    </p>
    <input type="submit" value="Wyślij">
</form>

</body>
</html>