<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="/style/scripts.js"></script>
    <link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/style/style2.css">
    <link rel="stylesheet" href="/style/gallery.css">
    <title>Odnowa Młodzi | Galeria</title>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar" data-offset="60">
<div class="loader"></div>
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigationbar">
                <span class="sr-only">Zmień</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="/">OdNowa Młodzi</a>
        </div>

        <div class="collapse navbar-collapse" id="navigationbar">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="/blog">BLOG</a>
                </li>
                <li>
                    <a class="page-scroll" href="/">STRONA GŁÓWNA</a>
                </li>
                <li>
                    <a href="https://www.facebook.com/OdNowaMlodzi/"><i class="fa fa-facebook-square fa-lg icon-fb"></i></a>
                </li>
                <li>
                    <a href="https://www.youtube.com/channel/UCUqIgEqFNYA0sd0eFkcm0Ug"><i class="fa fa-youtube-play fa-lg icon-yt"></i></a>
                </li>
                <li>
                    <a href="http://warmia.odnowa.org/"><img src="/images/log.png" alt="log" width="18px"></a>
                </li>
                <li>
                    <a href="/admin"><i class="fa fa-wrench fa-lg"></i></a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
<div class="container-fluid">
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-2">
        <ul class="list-group">
            <?php foreach($galleries as $gallery): ?>
                <a href=<?php print('"/gallery/index/'.$gallery->id.'/"'); ?>" class="list-group-item">
                <?php print($gallery->title); ?>
                    <span class="badge"></span>
                </a>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="row">
        <?php if(empty($content)): ?>
            <div class="col-md-12">
                <center><p>Witaj w naszej galerii! Wybierz kategorię po lewej i przeżyj wszystko jeszcze raz!</p></center>
            </div>
        <?php else: ?>

                <center><h2><?php print($galleries[$content-1]->title); ?></h2></center>
                <center>
            <?php foreach($images as $key=>$image): ?>
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <img src="<?php echo '/images/gallery/'.$image['url']; ?>" alt="" class="img-thumbnail image">
                </div>
            <?php endforeach; ?>
                </center>
            </div>
            <div class="row">
                <center>
                    <?php if($left): ?>
                        <a href=<?php print('"/gallery/index/' . $content . '/' . ($page - 1)); ?>" class=""> Wstecz </a>
                    <?php endif; ?>
                    <?php print($page); ?>
                    <?php if($right): ?>
                        <a href=<?php print('"/gallery/index/' . $content . '/' . ($page + 1)); ?>" class=""> Dalej </a>
                    <?php endif; ?>
                </center>
            </div>
        <?php endif; ?>
    </div>
</div>
</div>



</body>
</html>