<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="/style/scripts.js"></script>
    <link rel="stylesheet" href="/style/style2.css">
    <title>Odnowa Młodzi | Blog</title>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar" data-offset="60">
<div class="loader"></div>

<!--<nav id="mainNav" class="navbar navbar-default navbar-fixed-top" role="navigation">-->
<!--    <div class="container-fluid">-->
<!--        <div class="navbar-header">-->
<!--            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigationbar">-->
<!--                <span class="sr-only">Zmień</span>-->
<!--                <span class="icon-bar"></span>-->
<!--                <span class="icon-bar"></span>-->
<!--                <span class="icon-bar"></span>-->
<!--            </button>-->
<!--            <a class="navbar-brand page-scroll" href="/">OdNowa Młodzi</a>-->
<!--        </div>-->
<!---->
<!--        <div class="collapse navbar-collapse" id="navigationbar">-->
<!--            <ul class="nav navbar-nav navbar-right">-->
<!--                <li>-->
<!--                    <a class="page-scroll" href="#about">O NAS</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a class="page-scroll" href="#patronage">DUCHOWY PATRONAT</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a class="page-scroll" href="#evangelism">EWANGELIZACJA</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a class="page-scroll" href="#certificate">ŚWIADECTWA</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a class="page-scroll" href="#portfolio">GALERIA</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a class="page-scroll" href="#contact">KONTAKT</a>-->
<!--                </li>-->
<!--            </ul>-->
<!--        </div>-->
        <!-- /.navbar-collapse -->
<!--    </div>-->
    <!-- /.container-fluid -->
<!--</nav>-->


<div id="blog" class="container">
    <div class="row">
        <div class="col-sm-7 bg-grey">
            <?php foreach($posts as $key=>$post): ?>

            <div class="post-div">
                <div style="min-height: 200px; border: 1px solid grey;" class="text-center">tutoj zdjencie</div>

                <span class="post-title"><?php echo $post['title']; ?></span><br />
                <?php echo $users[$post['author_id']]; ?>
                <?php echo date('d.m.Y', strtotime($post['date'])); ?> <br />
                <p class="post-short">
                    <?php echo $post['text']; ?>
                </p>
                <?php echo '<a href="/blog/post/' . $post['id'] . '"><button type="button" class="btn post-button"><span>Czytaj </span></button></a>'; ?>
            </div><br />
            <?php endforeach;  ?>
        </div>
        <div class="col-sm-2">
        </div>
        <div class="col-sm-3" style="border: 1px solid black;">
            a tutaj mam prawy coś
        </div>
    </div>
</div>





<footer class="container-fluid text-center bg-grey">
    <a class="page-scroll" href="#page-top">
        <span class="glyphicon glyphicon-chevron-up"></span>
    </a>
    <p>Strona stworzona przez <a href="http://www.cutyris.net" title="Cutyris Dev Studio">Robert Galon</a></p>
</footer>

<script>
    $(document).ready(function(){
        $(".navbar a, footer a[href='#myPage']").on('click', function(event) {
            if (this.hash !== "") {
                event.preventDefault();

                var hash = this.hash;

                $('html, body').animate({
                    scrollTop: $(hash).offset().top
                }, 900, function(){
                    window.location.hash = hash;
                });
            }
        });

        $(window).scroll(function() {
            $(".slideanim").each(function(){
                var pos = $(this).offset().top;

                var winTop = $(window).scrollTop();
                if (pos < winTop + 600) {
                    $(this).addClass("slide");
                }
            });
        });
    })
</script>

</body>
</html>