<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="style/scripts.js"></script>
    <link rel="stylesheet" href="style/style2.css">
    <title>Odnowa Młodzi | Aktualności</title>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar" data-offset="60">

post
</body>
</html>